### ISSUE TITLE
HTML manual not working

### ISSUE THREAD

**Issue by mrustl** [jeroenooms/opencpu#189]
Hi  @jeroenooms, 

I realised that the following API endpoint is not working as expected: 

Running: http://public.opencpu.org/ocpu/library/tools/man/Rd2HTML/html 

Throws the following error message:

`could not find function "Rd2HTML"`

In call:
`man_html(rdfile, package = reqpackage, pkgpath = pkgpath)`

Endpoints "/pdf" or "/text" are working normally

**Comment by jeroenooms** [comment]
Thanks! I think this fixes it https://github.com/jeroenooms/opencpu/commit/805c67016af0d6d39d14c84a61b58a9ac8b16b88

**Comment by jeroenooms** [comment]
Fixed in 1.6.2:

https://public.opencpu.org/ocpu/library/jsonlite/man/fromJSON/text
https://public.opencpu.org/ocpu/library/jsonlite/man/fromJSON/pdf
https://public.opencpu.org/ocpu/library/jsonlite/man/fromJSON/html

Thanks!!

**Comment by Planeshifter** [comment]
Hi there, I ran into the same problem. Now, everything works when I make requests to `https://public.opencpu.org` or use the local single-user server in R using the current `opencpu` library. However, we are running our own  OpenCPU cloud server, and still experience this issue. Am I correct that this still needs to land in the `opencpu-server`? Any estimates when that might happen? Thanks for your great work!

**Comment by jeroenooms** [comment]
It should be there, which version of the opencpu server are you running?

**Comment by Planeshifter** [comment]
Adding the PPA on the OpenCPU webpage and upgrading the package solved the problem. We must have been running an outdated version.  Thanks for the quick response!
